# Generated by Django 4.2 on 2023-04-13 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vaccinetype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Vaccinecenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('address', models.TextField()),
                ('dose_type', models.CharField(choices=[('First Dose', 'First Dose'), ('Second Dose', 'Second Dose'), ('Booster Dose', 'Booster Dose')], default='First Dose', max_length=255)),
                ('vaccine_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vaccination_api.vaccinetype')),
            ],
        ),
    ]
